### PR TITLE
N&N for https://github.com/eclipse-platform/eclipse.platform.runtime/…

### PR DESCRIPTION
**Pull request by laeubi**
[…issues/43](https://github.com/eclipse-platform/eclipse.platform.runtime/issues/43)

### CODE REVIEW

**Comment by mickaelistria** [comment]
Can you please rework commit message to tell what it's about without having to click the link?

**Comment by laeubi** [comment]
> Can you please rework commit message to tell what it's about without having to click the link?

I think its obvious from the commit itself otherwise its not a good N&N entry isn't it?

**Comment by mickaelistria** [comment]
The goal or main content of the change must be summarized on the 1st line of commit message. Otherwise, why even having a commit message? Some people (I'm one of them) sometimes spend some time reading history of some projects, seeing who did what, what are the trends, without digging deeper than the 1st line of the commit.

**Comment by laeubi** [comment]
> The goal or main content of the change must be summarized on the 1st line of commit message.

Well the main goal for this change is having a N&N for the referenced issue :-)

**Review by vogella — APPROVED** [review]
LGTM, for the commit message qualitfy in N&N I personally don't care to much, for code the history is important but for N&N I don't think so.

**Comment by mickaelistria** [comment]
OK, I'm doing to do it myself to save the time of discussion here. But please read some tutorials about writing good Git commit messages, that will help saving time in the future.

**Comment by laeubi** [comment]
> Otherwise, why even having a commit message?

This is a good question, it would obviously better to manage the N&N in the repository of the source, so one could submit the N&N together with the change and then it is aggregated in some way, the current process it is kind of useless as there is no connection between change <-> N&N unless you give a link ...

**Comment by mickaelistria** [comment]
Merged as https://github.com/eclipse-platform/www.eclipse.org-eclipse-news/commit/1375128115ba69bc5fba5e4ceb524f9b54fb1fff

**Comment by vogella** [comment]
Opened https://github.com/eclipse-platform/www.eclipse.org-eclipse-news/issues/18 for the idea to use a wiki for the N&N.

**Pull request closed without merging**
