### PR TITLE
N&N about slf4j migration to Maven-Central

### PR DESCRIPTION
**Pull request by HannesWell**
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/588

@jonahgraham what do you think?

### CODE REVIEW

**Review by jonahgraham — APPROVED** [review]
LGTM - I think having this here will increase the likelihood that adopters see it. I think the other place it is needed is here: https://github.com/eclipse-platform/eclipse.platform.common/blob/master/bundles/org.eclipse.platform.doc.isv/porting/4.26/

**Comment by jonahgraham** [comment]
> LGTM - I think having this here will increase the likelihood that adopters see it. I think the other place it is needed is here: https://github.com/eclipse-platform/eclipse.platform.common/blob/master/bundles/org.eclipse.platform.doc.isv/porting/4.26/

I saw [this comment ](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/588#issuecomment-1325642152) after making the above comment. Glad to see you have this well in hand.

**Comment by HannesWell** [comment]
> LGTM - I think having this here will increase the likelihood that adopters see it. I think the other place it is needed is here: https://github.com/eclipse-platform/eclipse.platform.common/blob/master/bundles/org.eclipse.platform.doc.isv/porting/4.26/

Thanks.
Will do that tomorrow morning. Turned off my computer already.

**Comment by HannesWell** [comment]
@lshanmug is it ok, to enable this page again?

**Comment by lshanmug** [comment]
> @lshanmug is it ok, to enable this page again?

We can do that, but looks like this entry should go into platform_isv.html instead as it's about plugin/feature level changes?

**Comment by lshanmug** [comment]
> > LGTM - I think having this here will increase the likelihood that adopters see it. I think the other place it is needed is here: https://github.com/eclipse-platform/eclipse.platform.common/blob/master/bundles/org.eclipse.platform.doc.isv/porting/4.26/
> 
> Thanks. Will do that tomorrow morning. Turned off my computer already.

I think there are no more builds scheduled for 4.26 to pick any changes from the platform.common repo :(

**Comment by HannesWell** [comment]
> > @lshanmug is it ok, to enable this page again?
> 
> We can do that, but looks like this entry should go into platform_isv.html instead as it's about plugin/feature level changes?

I have to admit I'm note familiar with the details, which entry has to go where exactly, so I just trust your judgement and just move it. This only entry would have looked a bit lost on a new site any way.

**Comment by HannesWell** [comment]
> > > LGTM - I think having this here will increase the likelihood that adopters see it. I think the other place it is needed is here: https://github.com/eclipse-platform/eclipse.platform.common/blob/master/bundles/org.eclipse.platform.doc.isv/porting/4.26/
> > 
> > 
> > Thanks. Will do that tomorrow morning. Turned off my computer already.
> 
> I think there are no more builds scheduled for 4.26 to pick any changes from the platform.common repo :(

Too bad. But I assume the N&N are read by more people than the porting guide any way. So for this release others will notice through the N&N. I will add a porting entry for 4.26 nevertheless and it will be picked up in future releases so that it still can be looked up later. Or do you think this does not make sense then?

**Comment by jonahgraham** [comment]
> Or do you think this does not make sense then?

Please add it anyway, someone going from 4.24 -> 4.28 in the future will see it, especially as many adopters don't update to every version of the platform.

**Comment by HannesWell** [comment]
> > Or do you think this does not make sense then?
> 
> Please add it anyway, someone going from 4.24 -> 4.28 in the future will see it, especially as many adopters don't update to every version of the platform.

Yes, that's what I meant above. :)
Just did it:
https://github.com/eclipse-platform/eclipse.platform.common/pull/94

**Pull request merged**
