### PR TITLE
Carstenartur/master

### PR DESCRIPTION
**Pull request by jjohnstn**
This is a modified version of Carsten's patch.  Please squash to have Carsten's commit comment plus the fixes #47 line.

### CODE REVIEW

**Comment by carstenartur** [comment]
Just to be sure: you are aware that the extranous files have been there to be able to copy the sample sources from the N&N page? That was the way it had been done in early releases of Eclipse and then got lost somehow. Maybe in this case it is no need for it as it is small but I must say I miss this functionality sometimes and thought we could reintroduce it at this point.

**Comment by vogella** [comment]
@jjohnstn or @carstenartur let me know once I should merge this PR

**Comment by carstenartur** [comment]
Feel free to merge. We can take care about reintroducing code copy capabilites in N&N at a later point in time or not at all depending on your personal preference.

**Comment by jjohnstn** [comment]
Ok, thanks Carsten.  The code copy stuff should be handled in a separate PR/Issue.

**Comment by carstenartur** [comment]
> Ok, thanks Carsten.  The code copy stuff should be handled in a separate PR/Issue.

Shouldn't we merge this before the Final Release? The patch itself is merged already, isn't it?

**Comment by vogella** [comment]
Sorry @jjohnstn I was on holidays. Looks like @sravanlakkimsetti handled this one. Thanks Sravan.

**Pull request merged**
