### PR TITLE
N&N for Auto infix search in Open Resource

### PR DESCRIPTION
**Pull request by pbodnar**
See https://github.com/eclipse-platform/eclipse.platform.ui/pull/12

### CODE REVIEW

**Comment by pbodnar** [comment]
@mickaelistria / @vogella, can you please review? I guess the change in the `SearchPattern`'s API is not that noteworthy to be described as well, right?

**Comment by mickaelistria** [comment]
Thank you!

**Comment by vogella** [comment]
Thanks @pbodnar for all your work

**Comment by pbodnar** [comment]
You're welcome, thanks to both of you as well. :)

**Pull request merged**
