### PR TITLE
Add N&N for PDE Bundle/Version Annotations

### PR DESCRIPTION
**Pull request by laeubi**

### CODE REVIEW

**Comment by SarikaSinha** [comment]
@laeubi 
Can you please provide the github issue or bugzilla link in the N&N entry ?
instructions.html has the instructions to include them.
Not able to understand, how to edit the target platform as an editor ? Can you please explain. 

@vik-chand

**Comment by vik-chand** [comment]
> @laeubi Can you please provide the github issue or bugzilla link in the N&N entry ? instructions.html has the instructions to include them. Not able to understand, how to edit the target platform as an editor ? Can you please explain.
> 
> @vik-chand

If we are not able to understand this, then we will have to remove it from PDE N&N. Please provide steps/instructions by Wednesday ( 24th Aug).

**Comment by laeubi** [comment]
Issue is https://github.com/eclipse-pde/eclipse.pde/issues/69 / PR 
- https://github.com/eclipse-pde/eclipse.pde/pull/234
- https://github.com/eclipse-pde/eclipse.pde/pull/209

> Not able to understand, how to edit the target platform as an editor ? Can you please explain.

Explain what? Target Platform editor is not part of this change.

**Comment by SarikaSinha** [comment]
N&N should explain how this target platform editor can be accessed.

**Comment by laeubi** [comment]
> N&N should explain how this target platform editor can be accessed.

As mentioned this has nothing to do with target platform editor ... The target snippet is just an example and you could of course add it by other means, and I assume any PDE developer is familiar how to configure its target?

**Comment by vik-chand** [comment]
> > N&N should explain how this target platform editor can be accessed.
> 
> As mentioned this has nothing to do with target platform editor ... The target snippet is just an example and you could of course add it by other means, and I assume any PDE developer is familiar how to configure its target?

I think we can remove that part which is just plain confusing. ( at best we can mention that for older projects one need to configure target so as to add those bundles) . Morever in a new plugin project those 2 bundles are available by default. Rest of the N&N looks OK.

**Pull request merged**
