### PR TITLE
N&N for Javadoc inline @return tag support

### PR DESCRIPTION
**Pull request by jjohnstn**
See https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/340

### CODE REVIEW

**Comment by jjohnstn** [comment]
@akurtakov Please review

**Comment by jjohnstn** [comment]
@iloveeclipse please review as I don't have write access.

**Comment by iloveeclipse** [comment]
@jjohnstn : there is a merge issue to be solved.

**Comment by akurtakov** [comment]
Sorry, I missed that one!

**Comment by akurtakov** [comment]
Looks good.

**Pull request merged**
