### PR TITLE
Add entry about PDE launching improvements

### PR DESCRIPTION
**Pull request by HannesWell**
New and noteworthy entry for the improvements in the area of PDE product/application launching.

Please let me know if you have any suggestions for improvements.

Spell-check and html check are still pending.

@vogella or anybody else, what do you think?
I wonder if the last part is a bit to verbose,

### CODE REVIEW

**Comment by HannesWell** [comment]
I have adjusted the text a bit and completed spell-check and validation. So for me this is ready.

@vogella, @vik-chand, @jhonnen do you have suggestions for improvements?

**Comment by vogella** [comment]
LGTM, thanks Hannes.

**Comment by vik-chand** [comment]
> I have adjusted the text a bit and completed spell-check and validation. So for me this is ready.
> 
> @vogella, @vik-chand, @jhonnen do you have suggestions for improvements?

LGTM

If required, we can improve the text in RC1

**Comment by vik-chand** [comment]
@HannesWell can you please commit this change post fixing merge issues?

**Comment by HannesWell** [comment]
Thanks for your feedback.

Rebased it, resolved the merge conflicts and commented the editors section in again (since I added items).
Validation still succeeds.

**Pull request merged**
